export const DELIVERY_PARTNER_AUDIT_ENTITY_TYPE = "DELIVERY_PARTNER" as const;

export const DELIVERY_PARTNER_ACTIONS = {
  CREATE: "DELIVERY_PARTNER_CREATE",
  UPDATE: "DELIVERY_PARTNER_UPDATE",
  DISABLE: "DELIVERY_PARTNER_DISABLE",
  ENABLE: "DELIVERY_PARTNER_ENABLE",
} as const;

export const DELIVERY_PARTNER_SORT_FIELDS = [
  "createdAt",
  "updatedAt",
  "city",
  "state",
  "country",
] as const;

export type DeliveryPartnerSortField =
  (typeof DELIVERY_PARTNER_SORT_FIELDS)[number];

export const DELIVERY_PARTNER_DEFAULT_PAGE = 1;
export const DELIVERY_PARTNER_DEFAULT_LIMIT = 20;
export const DELIVERY_PARTNER_MAX_LIMIT = 100;
export const DELIVERY_PARTNER_SEARCH_MAX_LENGTH = 120;
export const DELIVERY_PARTNER_REASON_MAX_LENGTH = 500;

export const DELIVERY_PARTNER_NOTIFICATION_TYPES = {
  CREATED: "DELIVERY_PARTNER_CREATED",
  DISABLED: "DELIVERY_PARTNER_DISABLED",
  ENABLED: "DELIVERY_PARTNER_ENABLED",
} as const;
