export const SELLER_ADDRESS_AUDIT_ENTITY_TYPE = "SELLER_ADDRESS" as const;

export const SELLER_ADDRESS_ACTIONS = {
  CREATE: "SELLER_ADDRESS_CREATE",
  UPDATE: "SELLER_ADDRESS_UPDATE",
  DELETE: "SELLER_ADDRESS_DELETE",
  DISABLE: "SELLER_ADDRESS_DISABLE",
  SET_DEFAULT: "SELLER_ADDRESS_SET_DEFAULT",
} as const;

export const SELLER_ADDRESS_SORT_FIELDS = [
  "createdAt",
  "updatedAt",
  "label",
  "city",
  "isDefault",
] as const;

export type SellerAddressSortField =
  (typeof SELLER_ADDRESS_SORT_FIELDS)[number];

export const SELLER_ADDRESS_DEFAULT_PAGE = 1;
export const SELLER_ADDRESS_DEFAULT_LIMIT = 20;
export const SELLER_ADDRESS_MAX_LIMIT = 100;

export const SELLER_ADDRESS_LABEL_MAX_LENGTH = 120;
export const SELLER_ADDRESS_CONTACT_MAX_LENGTH = 120;
export const SELLER_ADDRESS_PHONE_MAX_LENGTH = 20;
export const SELLER_ADDRESS_LINE_MAX_LENGTH = 200;
export const SELLER_ADDRESS_CITY_MAX_LENGTH = 100;
export const SELLER_ADDRESS_STATE_MAX_LENGTH = 100;
export const SELLER_ADDRESS_COUNTRY_MAX_LENGTH = 100;
