export const SETTLEMENT_AUDIT_ENTITY_TYPE = "SETTLEMENT_BATCH";

export const SETTLEMENT_ACTIONS = {
  BATCH_CREATED: "SETTLEMENT_BATCH_CREATED",
  BATCH_DISBURSED: "SETTLEMENT_BATCH_DISBURSED",
  COMMISSION_UPDATED: "SELLER_COMMISSION_UPDATED",
} as const;

export const SETTLEMENT_NOTIFICATION_TYPES = {
  BATCH_CREATED: "SETTLEMENT_BATCH_CREATED",
  BATCH_DISBURSED: "SETTLEMENT_BATCH_DISBURSED",
} as const;

export const SETTLEMENT_NOTIFICATION_EVENTS = {
  BATCH_CREATED: "SETTLEMENT_BATCH_CREATED",
  BATCH_DISBURSED: "SETTLEMENT_BATCH_DISBURSED",
} as const;

export const SETTLEMENT_BATCH_NUMBER_PREFIX = "SB";

export const SETTLEMENT_SORT_FIELDS = [
  "createdAt",
  "disbursedAt",
  "batchNumber",
  "grossAmount",
  "netAmount",
] as const;

export type SettlementSortField = (typeof SETTLEMENT_SORT_FIELDS)[number];

export const SETTLEMENT_DEFAULT_PAGE = 1;
export const SETTLEMENT_DEFAULT_LIMIT = 20;
export const SETTLEMENT_MAX_LIMIT = 100;
