export const DELIVERY_PARTNER_REVIEW_AUDIT_ENTITY_TYPE =
  "DELIVERY_PARTNER_REVIEW" as const;

export const DELIVERY_PARTNER_REVIEW_ACTIONS = {
  CREATE: "DELIVERY_PARTNER_REVIEW_CREATE",
  UPDATE: "DELIVERY_PARTNER_REVIEW_UPDATE",
  APPROVE: "DELIVERY_PARTNER_REVIEW_APPROVE",
  DISABLE: "DELIVERY_PARTNER_REVIEW_DISABLE",
} as const;

export const DELIVERY_PARTNER_REVIEW_MIN_RATING = 1;
export const DELIVERY_PARTNER_REVIEW_MAX_RATING = 5;
export const DELIVERY_PARTNER_REVIEW_COMMENT_MAX_LENGTH = 2000;
