export const NOTIFICATION_CHANNELS = {
  EMAIL: "EMAIL",
  IN_APP: "IN_APP",
} as const;

export type NotificationChannel =
  (typeof NOTIFICATION_CHANNELS)[keyof typeof NOTIFICATION_CHANNELS];

export const NOTIFICATION_EVENTS = {
  SELLER_APPROVED: "SELLER_APPROVED",
  SELLER_REJECTED: "SELLER_REJECTED",
  PRODUCT_APPROVED: "PRODUCT_APPROVED",
  PRODUCT_REJECTED: "PRODUCT_REJECTED",
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  SETTLEMENT_BATCH_CREATED: "SETTLEMENT_BATCH_CREATED",
  SETTLEMENT_BATCH_DISBURSED: "SETTLEMENT_BATCH_DISBURSED",
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENTS)[keyof typeof NOTIFICATION_EVENTS];

export const NOTIFICATION_TYPES = {
  SELLER_APPROVED: "SELLER_APPROVED",
  SELLER_REJECTED: "SELLER_REJECTED",
  SELLER_DISABLED: "SELLER_DISABLED",
  SELLER_ENABLED: "SELLER_ENABLED",
  PRODUCT_APPROVED: "PRODUCT_APPROVED",
  PRODUCT_REJECTED: "PRODUCT_REJECTED",
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  DELIVERY_ASSIGNED: "DELIVERY_ASSIGNED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  SETTLEMENT_BATCH_CREATED: "SETTLEMENT_BATCH_CREATED",
  SETTLEMENT_BATCH_DISBURSED: "SETTLEMENT_BATCH_DISBURSED",
} as const;

export const NOTIFICATION_DEFAULT_PAGE = 1;
export const NOTIFICATION_DEFAULT_LIMIT = 20;
export const NOTIFICATION_MAX_LIMIT = 100;

export const NOTIFICATION_SORT_FIELDS = ["createdAt"] as const;
export type NotificationSortField =
  (typeof NOTIFICATION_SORT_FIELDS)[number];

export const NOTIFICATION_RETRY = {
  MAX_ATTEMPTS: 3,
  BASE_DELAY_MS: 300,
} as const;
