import { EMAIL_TEMPLATE_IDS } from "../../email/constants/email.constants.js";
import { NOTIFICATION_EVENTS } from "./notification.constants.js";

export const NOTIFICATION_EMAIL_TEMPLATE_MAP = {
  [NOTIFICATION_EVENTS.SELLER_APPROVED]: EMAIL_TEMPLATE_IDS.SELLER_APPROVED,
  [NOTIFICATION_EVENTS.SELLER_REJECTED]: EMAIL_TEMPLATE_IDS.SELLER_REJECTED,
  [NOTIFICATION_EVENTS.PRODUCT_APPROVED]: EMAIL_TEMPLATE_IDS.PRODUCT_APPROVED,
  [NOTIFICATION_EVENTS.PRODUCT_REJECTED]: EMAIL_TEMPLATE_IDS.PRODUCT_REJECTED,
  [NOTIFICATION_EVENTS.ORDER_PLACED]: EMAIL_TEMPLATE_IDS.ORDER_PLACED,
  [NOTIFICATION_EVENTS.ORDER_CANCELLED]: EMAIL_TEMPLATE_IDS.ORDER_CANCELLED,
  [NOTIFICATION_EVENTS.DELIVERY_ASSIGNED]:
    EMAIL_TEMPLATE_IDS.DELIVERY_ASSIGNED,
  [NOTIFICATION_EVENTS.ORDER_DELIVERED]: EMAIL_TEMPLATE_IDS.ORDER_DELIVERED,
} as const;
